development: &development
  papers:
    com_myrepublica:
      class_name: ComMyrepublica
      enabled: true
    com_nagariknews:
      class_name: ComNagariknews
      enabled: true
    xyz:
      class_name: Dummy
      enabled: false

  pdf_write_dir: tmp/pdf_out

  tmp_dir: tmp

  thumbnail_write_dir: tmp/thumbnail_out

test: 
  <<: *development
  pdf_write_dir: tmp/pdf_out_test
  thumbnail_write_dir: tmp/thumbnail_out_test

production: 
  <<: *development
  pdf_write_dir: /app/pdf_out