development: &development
  papers:
    base: &base
      enabled: false

    com_myrepublica:
      <<: *base
      enabled: true

    com_nagariknews:
      <<: *base
      enabled: true

    com_thehimalayantimes:
      <<: *base
      enabled: true

    com_ekantipur:
      <<: *base
      enabled: true

    com_ekantipur_kpost:
      <<: *base
      enabled: true


  pdf_write_dir: tmp/public/pdf
  thumbnail_write_dir: tmp/public/thumbnail
  tmp_dir: tmp


test: 
  <<: *development
  pdf_write_dir: tmp/pdf_out_test
  thumbnail_write_dir: tmp/thumbnail_out_test

production: 
  <<: *development
  static_dir: /data/bharkharapp/public
  pdf_write_dir: /data/bharkharapp/public/pdf
  thumbnail_write_dir: /data/bharkharapp/public/thumbnail
